# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration                +
# project    nord-java                                    +
# version    0.0.0                                        +
# repository https://github.com/arcticicestudio/nord-java +
# author     Arctic Ice Studio                            +
# email      development@arcticicestudio.com              +
# copyright  Copyright (C) 2016                           +
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI Documentation
#   (https://docs.travis-ci.com)
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
 directories:
    - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
script: mvn -B test -P code-coverage
